# Generated by Django 3.1.3 on 2020-11-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20201124_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
    ]
